[package]
distribution = "2201.7.2"
org = "ballerinax"
name = "ai.agent"
version = "0.5.5"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AI/Agent", "Cost/Freemium"]
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.agent"

[build-options]
observabilityIncluded = true
