[package]
distribution = "2201.11.0"
org = "ballerinax"
name = "ai.agent"
version = "0.7.9"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AI/Agent", "Cost/Freemium", "Agent", "AI"]
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.agent"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.agent-native"
version = "0.7.9"
path = "../native/build/libs/ai.agent-native-0.7.9-SNAPSHOT.jar"
