[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "ai"
version = "1.0.1"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AI/Agent", "Cost/Freemium", "Agent", "AI"]
repository = "https://github.com/ballerina-platform/module-ballerinax-ai"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai-native"
version = "1.0.1"
path = "../native/build/libs/ai-native-1.0.1-SNAPSHOT.jar"
