[plugin]
id = "ai-compiler-plugin"
class = "io.ballerina.lib.ai.plugin.AiCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/ai-compiler-plugin-1.0.1-SNAPSHOT.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-2.3.0.jar"
