name: CI

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: check_connector_for_breaking_changes
  workflow_dispatch:

jobs:
  call_workflow:
    name: Run Connector Build Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/build-connector-template.yml@main
    secrets: inherit
    with:
      repo-name: module-ballerinax-ai.agent
      publish-required: true
